services:
  - type: web
    name: puebla-mapa
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python -m gunicorn puebla_mapa.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
